DROP TABLE IF EXISTS HEXAMOD.TASKS;

CREATE TABLE HEXAMOD.TASKS(
		identificador VARCHAR(36) PRIMARY KEY NOT NULL,
		usuario VARCHAR(36) NOT NULL,
		descripcion VARCHAR(100) NOT NULL,
		duracion INTEGER NOT NULL
	);
